<?php
/**
 * @var \Mageplaza\HelloWorld\Block\Display $block
 */
?>
<h2>The stores around you</h2>
<div id="map"></div>
<div id="stores"></div>
<style>
    #map {
        width: 100%;
        height: 400px;
        background-color: grey;
    }
</style>

<script type="text/x-magento-init">
    {
        "#stores": {
            "ninjaStores": {
                "url": "<?php echo $block->getUrl('ninja/stores') ?>",
                "map": "#map"
            }
        }
    }
</script>

<script async defer src="https://maps.googleapis.com/maps/api/js?key=
AIzaSyD1cxIBCzncxDL89MUOtgexZR7wetqW-vo
&callback=initMap">
</script>
